### ISSUE TITLE
💩

### ISSUE THREAD

**Issue by aderyabin** [datacrafts-io/skeleton#8]
What are the benefits to use the gem instead of [Rails Application Templates](https://guides.rubyonrails.org/rails_application_templates.html) or [Rails Templates](https://github.com/mattbrictson/rails-template) or [many other similar tools](https://www.ruby-toolbox.com/categories/rails_app_templates)?

**Comment by akurashev** [comment]
This gem uses Rails Application Templates under the hood to generate backend part.
In addition it includes frontend part generating as well using Vue or React CLI tools.

In result you get Rails in API-only mode for backend and a completely standalone Vue/React frontend app, both with some set of useful gems/js libs.
If one's supposed architecture fits this pattern then they can try this gem.
